name: flutter_bloc_page_template
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/chalermpong/flutter_bloc_page_template

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
